import type { NHLPositionCategory } from '@/types/nhl-player.ts'

export interface NHLHOFStatAverage {
  mean: number
  median: number
}

export interface NHLHOFSkaterPositionalStats {
  sampleSize: number
  stats: {
    gamesPlayed: NHLHOFStatAverage
    goals: NHLHOFStatAverage
    assists: NHLHOFStatAverage
    points: NHLHOFStatAverage
    plusMinus: NHLHOFStatAverage
    pim: NHLHOFStatAverage
    powerPlayGoals: NHLHOFStatAverage
    powerPlayPoints: NHLHOFStatAverage
    shorthandedGoals: NHLHOFStatAverage
    shorthandedPoints: NHLHOFStatAverage
    gameWinningGoals: NHLHOFStatAverage
    shots: NHLHOFStatAverage
    shootingPctg: NHLHOFStatAverage
    faceoffWinningPctg: NHLHOFStatAverage
  }
}

export interface NHLHOFGoaliePositionalStats {
  sampleSize: number
  stats: {
    gamesPlayed: NHLHOFStatAverage
    gamesStarted: NHLHOFStatAverage
    wins: NHLHOFStatAverage
    losses: NHLHOFStatAverage
    otLosses: NHLHOFStatAverage
    goalsAgainstAvg: NHLHOFStatAverage
    savePctg: NHLHOFStatAverage
    shutouts: NHLHOFStatAverage
    shotsAgainst: NHLHOFStatAverage
    goalsAgainst: NHLHOFStatAverage
  }
}

export type NHLHOFPositionalStats = NHLHOFSkaterPositionalStats | NHLHOFGoaliePositionalStats

/**
 * Real computed career stat averages for Hockey Hall of Fame inductees,
 * grouped by position. Mean uses weighted averaging for rate stats.
 * Generated by: node scripts/compute-nhl-hof-averages.cjs
 */
export const NHL_HOF_POSITIONAL_STATS: Record<NHLPositionCategory, NHLHOFPositionalStats> = {
  C: {
    sampleSize: 39,
    stats: {
      gamesPlayed: { mean: 1250.7, median: 1282 },
      goals: { mean: 487.7, median: 490 },
      assists: { mean: 833, median: 813 },
      points: { mean: 1320.7, median: 1281 },
      plusMinus: { mean: 135, median: 114 },
      pim: { mean: 816.1, median: 820 },
      powerPlayGoals: { mean: 145.4, median: 150 },
      powerPlayPoints: { mean: 443, median: 432 },
      shorthandedGoals: { mean: 19.9, median: 12 },
      shorthandedPoints: { mean: 36.4, median: 31 },
      gameWinningGoals: { mean: 68.8, median: 68 },
      shots: { mean: 2923.2, median: 3068 },
      shootingPctg: { mean: 0.15, median: 0.15 },
      faceoffWinningPctg: { mean: 0.52, median: 0.53 },
    },
  },
  LW: {
    sampleSize: 15,
    stats: {
      gamesPlayed: { mean: 1188.1, median: 1089 },
      goals: { mean: 464.8, median: 424 },
      assists: { mean: 536.8, median: 570 },
      points: { mean: 1001.6, median: 1041 },
      plusMinus: { mean: 112.2, median: 71 },
      pim: { mean: 861.1, median: 743 },
      powerPlayGoals: { mean: 137.3, median: 138 },
      powerPlayPoints: { mean: 312.9, median: 324 },
      shorthandedGoals: { mean: 12.4, median: 11 },
      shorthandedPoints: { mean: 19.1, median: 16 },
      gameWinningGoals: { mean: 66.5, median: 63 },
      shots: { mean: 2248.5, median: 2403 },
      shootingPctg: { mean: 0.14, median: 0.13 },
      faceoffWinningPctg: { mean: 0.39, median: 0.39 },
    },
  },
  RW: {
    sampleSize: 24,
    stats: {
      gamesPlayed: { mean: 1137.7, median: 1127.5 },
      goals: { mean: 514.7, median: 501 },
      assists: { mean: 610.4, median: 612 },
      points: { mean: 1125.1, median: 1112.5 },
      plusMinus: { mean: 114.6, median: 67.5 },
      pim: { mean: 701.9, median: 584.5 },
      powerPlayGoals: { mean: 157.6, median: 150.5 },
      powerPlayPoints: { mean: 374.3, median: 361.5 },
      shorthandedGoals: { mean: 14.3, median: 12 },
      shorthandedPoints: { mean: 22.4, median: 17.5 },
      gameWinningGoals: { mean: 75.8, median: 73 },
      shots: { mean: 2938, median: 3136 },
      shootingPctg: { mean: 0.15, median: 0.15 },
      faceoffWinningPctg: { mean: 0.37, median: 0.38 },
    },
  },
  D: {
    sampleSize: 31,
    stats: {
      gamesPlayed: { mean: 1236.9, median: 1254 },
      goals: { mean: 207.8, median: 208 },
      assists: { mean: 620.4, median: 590 },
      points: { mean: 828.1, median: 787 },
      plusMinus: { mean: 251.1, median: 260 },
      pim: { mean: 1142.5, median: 893 },
      powerPlayGoals: { mean: 80.4, median: 81 },
      powerPlayPoints: { mean: 341.5, median: 324 },
      shorthandedGoals: { mean: 8.1, median: 6 },
      shorthandedPoints: { mean: 25.1, median: 21 },
      gameWinningGoals: { mean: 29.3, median: 29 },
      shots: { mean: 2701, median: 2765 },
      shootingPctg: { mean: 0.07, median: 0.07 },
      faceoffWinningPctg: { mean: 0.36, median: 0.36 },
    },
  },
  G: {
    sampleSize: 15,
    stats: {
      gamesPlayed: { mean: 826.9, median: 868 },
      gamesStarted: { mean: 807.1, median: 832 },
      wins: { mean: 416.2, median: 407 },
      losses: { mean: 269.3, median: 295 },
      otLosses: { mean: 17.5, median: 0 },
      goalsAgainstAvg: { mean: 2.62, median: 2.52 },
      savePctg: { mean: 0.9078, median: 0.9102 },
      shutouts: { mean: 63.1, median: 66 },
      shotsAgainst: { mean: 19719.5, median: 22079 },
      goalsAgainst: { mean: 2097.7, median: 2223 },
    },
  },
}
